services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: php
    volumes:
      - ./:/var/www/html/
    depends_on:
      - webserver
  webserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: nginx 
    ports:
      - "8080:80"